version: "3.8"
services:
  web:
    image: nginx:alpine
    container_name: manunggal
    ports:
      - "5500:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
